// constants.js
export const cities = [
  { value: "Hanoi", label: "Hà Nội" },
  { value: "Ho Chi Minh", label: "TP. Hồ Chí Minh" },
  { value: "Hai Phong", label: "Hải Phòng" },
  { value: "Da Nang", label: "Đà Nẵng" },
  { value: "Hue", label: "Huế" },
  { value: "Vinh", label: "Vinh" },
  { value: "Bien Hoa", label: "Biên Hòa" },
  { value: "Nha Trang", label: "Nha Trang" },
  { value: "Da Lat", label: "Đà Lạt" },
  { value: "Ha Giang", label: "Hà Giang" },
  { value: "Cao Bang", label: "Cao Bằng" },
  { value: "Bac Kan", label: "Bắc Kạn" },
  { value: "Tuyen Quang", label: "Tuyên Quang" },
  { value: "Lao Cai", label: "Lào Cai" },
  { value: "Dien Bien", label: "Điện Biên" },
  { value: "Lai Chau", label: "Lai Châu" },
  { value: "Son La", label: "Sơn La" },
  { value: "Yen Bai", label: "Yên Bái" },
  { value: "Thai Nguyen", label: "Thái Nguyên" },
  { value: "Lang Son", label: "Lạng Sơn" },
  { value: "Bac Giang", label: "Bắc Giang" },
  { value: "Phu Tho", label: "Phú Thọ" },
  { value: "Vinh Phuc", label: "Vĩnh Phúc" },
  { value: "Bac Ninh", label: "Bắc Ninh" },
  { value: "Hai Duong", label: "Hải Dương" },
  { value: "Hung Yen", label: "Hưng Yên" },
  { value: "Thai Binh", label: "Thái Bình" },
  { value: "Ha Nam", label: "Hà Nam" },
  { value: "Nam Dinh", label: "Nam Định" },
  { value: "Ninh Binh", label: "Ninh Bình" },
  { value: "Thanh Hoa", label: "Thanh Hóa" },
  { value: "Nghe An", label: "Nghệ An" },
  { value: "Ha Tinh", label: "Hà Tĩnh" },
  { value: "Quang Binh", label: "Quảng Bình" },
  { value: "Quang Tri", label: "Quảng Trị" },
  { value: "Quang Nam", label: "Quảng Nam" },
  { value: "Quang Ngai", label: "Quảng Ngãi" },
  { value: "Binh Dinh", label: "Bình Định" },
  { value: "Phu Yen", label: "Phú Yên" },
  { value: "Khanh Hoa", label: "Khánh Hòa" },
  { value: "Gia Lai", label: "Gia Lai" },
  { value: "Kon Tum", label: "Kon Tum" },
  { value: "Binh Phuoc", label: "Bình Phước" },
  { value: "Dak Lak", label: "Đắk Lắk" },
  { value: "Dak Nong", label: "Đắk Nông" },
  { value: "Lam Dong", label: "Lâm Đồng" },
  { value: "Binh Duong", label: "Bình Dương" },
  { value: "Dong Nai", label: "Đồng Nai" },
  { value: "Ba Ria Vung Tau", label: "Bà Rịa – Vũng Tàu" },
  { value: "Long An", label: "Long An" },
  { value: "Tien Giang", label: "Tiền Giang" },
  { value: "Ben Tre", label: "Bến Tre" },
  { value: "Tra Vinh", label: "Trà Vinh" },
  { value: "Vinh Long", label: "Vĩnh Long" },
  { value: "Cao Lanh", label: "Cao Lãnh" },
  { value: "Sa Dec", label: "Sa Đéc" },
  { value: "Hong Ngu", label: "Hồng Ngự" },
  { value: "An Giang", label: "An Giang" },
  { value: "Kien Giang", label: "Kiên Giang" },
  { value: "Can Tho", label: "Cần Thơ" },
  { value: "Hau Giang", label: "Hậu Giang" },
  { value: "Soc Trang", label: "Sóc Trăng" },
  { value: "Bac Lieu", label: "Bạc Liêu" },
  { value: "Ca Mau", label: "Cà Mau" },
];
export const API_KEY = "022bc4eb98ba2192d16fa8286ed17a2f";